services:
  frontend:
    container_name: survivor-frontend
    build:
      context: ./frontend
    environment:
      BACKEND_URL: http://survivor-backend:8080
    ports:
      - "3000:3000"
    networks:
      - survivor
    depends_on:
      - backend

  backend:
    container_name: survivor-backend
    build:
      context: ./backend
    environment:
      DB_URL: postgres://postgres:${POSTGRES_PASSWORD}@survivor-postgres:5432/postgres
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "0.0.0.0:8080:8080"
    networks:
      - survivor
      - db
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: survivor-postgres
    image: postgres:18.6
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      - db
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s
      timeout: 5s
      retries: 20

networks:
  survivor:
  db:

volumes:
  postgres_data:
