[project]
name = "backend-scripts"
version = "0.1.0"
description = "Scripts for Survivor backend"
requires-python = ">=3.12"
dependencies = [
    "requests>=2.34.2",
]

[project.scripts]
verify_user_ids = "filtering.verify_user_ids:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"

[tool.uv.build-backend]
module-name = ["filtering.verify_user_ids"]
module-root = ""
