definitions:
  models.Answer:
    properties:
      answer:
        type: string
      correct:
        type: boolean
      question_id:
        type: integer
    type: object
  models.ApiError:
    properties:
      message:
        type: string
    type: object
  models.ApiMessage:
    properties:
      message:
        type: string
    type: object
  models.Question:
    properties:
      answers:
        items:
          $ref: '#/definitions/models.Answer'
        type: array
      question:
        type: string
      survey_id:
        type: integer
    type: object
  models.Survey:
    properties:
      obtention_rate:
        type: integer
      questions:
        items:
          $ref: '#/definitions/models.Question'
        type: array
    type: object
  routes.loginBody:
    properties:
      mail:
        type: string
      password:
        type: string
    required:
    - mail
    - password
    type: object
  routes.loginResponse:
    properties:
      token:
        type: string
    type: object
  routes.registerBody:
    properties:
      age:
        type: integer
      first_name:
        type: string
      last_name:
        type: string
      mail:
        type: string
      password:
        type: string
      role:
        type: integer
    required:
    - age
    - first_name
    - last_name
    - mail
    - password
    - role
    type: object
info:
  contact: {}
paths:
  /account/login:
    post:
      consumes:
      - application/json
      description: Account login endpoint
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.loginBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/routes.loginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Account login endpoint
      tags:
      - Account
  /account/register:
    post:
      consumes:
      - application/json
      description: Account register endpoint
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/routes.registerBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ApiMessage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Account register endpoint
      tags:
      - Account
  /ping:
    get:
      consumes:
      - application/json
      description: Simply says pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ApiMessage'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: ping
      tags:
      - Utils
  /ping/auth:
    get:
      consumes:
      - application/json
      description: Simply says pong
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ApiMessage'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: ping
      tags:
      - Utils
  /survey:
    get:
      consumes:
      - application/json
      description: Get the full survey
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Survey'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Get the full survey
      tags:
      - Survey
    post:
      consumes:
      - application/json
      description: Initialize the first survey
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Survey'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Survey'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Initialize the first survey
      tags:
      - Survey
    put:
      consumes:
      - application/json
      description: Modify the survey
      parameters:
      - description: Request body
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/models.Survey'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Survey'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/models.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/models.ApiError'
      summary: Modify the survey
      tags:
      - Survey
swagger: "2.0"
